config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "products#index"

  get "/pages/:page" => "pages#show"

  namespace :admin do
    resources :products do
      member do
        post :onsale
        post :notsale
      end
      resources :photos, :only => [:destroy]
    end

    resources :banners do
      member do
        post :hide
        post :publish
        post :do_slide
        post :undo_slide
      end
    end

    resources :categories do
      member do
        get :get_subcategories, defaults: { format: "js" }
      end
    end

  end  # namespace admin end

  resources :banners

  resources :products do
    member do
      post :add_to_cart
    end

    collection do
      get :search
      get :new_arrived
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders

  namespace :account do
    resources :orders
  end


  #resources :brands
  resources :categories


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :cover, CoverUploader
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    item = cart_items.where("product_id = ?", product.id)

    if item.size < 1
      ci = cart_items.build
      ci.product = product
      ci.quantity = 1
    else
      ci = item.first
      ci.update_attribute(:quantity, ci.quantity + 1)
    end

    product.quantity -= 1
    product.save

    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    return sum
  end

  def item_total_price(cart_item)
    # item = cart_items.where("product_id = ?", product.id)
    sum = 0

    if cart_item.product.price.present?
      sum += cart_item.quantity * cart_item.product.price
    end

    return sum
  end


  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :presence => true

  scope :main_categories, -> { where(:is_main_category => true) }
  scope :sub_categories, -> { where(:is_main_category => false) }

  has_many :products

  belongs_to :parent_category, :class_name => :Category, :foreign_key => "parent_category_id"
  has_many :children_categories,
          -> { where :is_main_category => false},
          :class_name => :Category,
          :foreign_key => :parent_category_id,
          :primary_key => :id

  def parent_category_name
    self.try(:parent_category).try(:name)
  end



end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lists
  before_create :generate_token

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :order
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  #mount_uploader :photo, PhotoUploader
  belongs_to :category
  belongs_to :brand
  has_many :photos
  accepts_nested_attributes_for :photos

  def onsale!
    self.onsale = true
    self.save
  end

  def notsale!
    self.onsale = false
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
    is_admin
  end

end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :require_is_admin
  layout "admin"

  def index
    @banners = Banner.all.order("created_at DESC")
  end

  def new
    @banner = Banner.new
  end

  def create 
    @banner = Banner.new(banner_params)

    if @banner.save
      redirect_to admin_banners_path, notice: "Banner Created."
    else
      render :new
    end
  end

  def edit
    @banner = Banner.find(params[:id])
  end

  def update
    @banner = Banner.find(params[:id])
    if @banner.update(banner_params)
      redirect_to admin_banners_path, :notice => "Banner Updated"
    else
      render :edit
    end
  end

  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy
    flash[:danger] = "Banner Deleted."
    redirect_to admin_banners_path
  end

  def hide
    @banner = Banner.find(params[:id])
    @banner.is_hidden = true
    @banner.save
    redirect_to :back
  end

  def publish
    @banner = Banner.find(params[:id])
    @banner.is_hidden = false
    @banner.save
    redirect_to :back
  end

  def do_slide
    @banner = Banner.find(params[:id])
    @banner.is_slide = true
    @banner.save
    redirect_to :back
  end

  def undo_slide
    @banner = Banner.find(params[:id])
    @banner.is_slide = false 
    @banner.save
    redirect_to :back
  end

  private

    def banner_params
      params.require(:banner).permit(:title, :description, :cover, :link, :is_slide, :is_hidden)
    end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end
end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
  def render_banner_is_hidden(banner)
    if !banner.is_hidden
      content_tag(:span, "", :class => "fa fa-globe")
    else
      content_tag(:span, "", :class => "fa fa-lock")
    end
  end

  def render_banner_is_slide(banner)
    if !banner.is_slide
      content_tag(:span, "", :class => "fa fa-image")
    else
      content_tag(:span, "", :class => "fa fa-video-camera")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def render_cart_total_price(cart)
    cart.total_price
  end

  def render_cart_item_total_price(cart, cart_item)
    cart.item_total_price(cart_item)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/banners/edit.html.erb
<h2>Edit Banner</h2>

<%= render "common/admin_banner_form" %>

app/views/admin/banners/index.html.erb
<h2>Banner List</h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增 Banner", new_admin_banner_path, class: "btn btn-primary btn-sm" ) %>
</div>
<div style="clear:both; font-size: 0.8em; color: #666;">
	<p>设为幻灯片：为首页轮播广告 Banner</p>
	<p>取消幻灯片：为首页轮播广告右侧两副小的 Banner</p>
	<p>隐藏与发布：设置是否在首页显示</p>
</div>

<table class="table table-bordered">
	<thead>
		<tr>
			<th width="70">#</th>
			<th width="150">Cover Img</th>
			<th>Title</th>
			<th>Description</th>
			<th width="250">Options</th>
		</tr>
	</thead>

	<tbody>
	  <% @banners.each do |banner| %>
		<tr>
			<td>
				<%= banner.id %>
				<%= render_banner_is_hidden(banner) %>
				<%= render_banner_is_slide(banner) %>
			</td>
			<td>
				<%= link_to admin_banner_path(banner) do %>
				  <% if banner.cover.present? %>
					  <%= image_tag(banner.cover.thumb.url, class: "thumbnail") %>
				  <% else %>
					  <%= image_tag("no-pic.png", class: "thumbnail") %>
				  <% end %>
				<% end %>
			</td>
			<td><%= banner.title %></td>
			<td><%= banner.description %></td>
			<td>
				<%= link_to("Edit", edit_admin_banner_path(banner), class: "btn btn-primary btn-xs") %>
				<%= link_to("Delete", admin_banner_path(banner), method: :delete, class: "btn btn-danger btn-xs", data: {confirm: "确定要删除该 Banner 吗？\n#{banner.title}" }) %>
			  <% if !banner.is_hidden %>
				<%= link_to("隐藏", hide_admin_banner_path(banner), method: :post, class: "btn btn-info btn-xs") %>
			  <% else %>
				<%= link_to("发布", publish_admin_banner_path(banner), method: :post, class: "btn btn-info btn-xs")  %>
			  <% end %>
			  <% if !banner.is_slide %>
				<%= link_to("设为幻灯片", do_slide_admin_banner_path(banner), method: :post, class: "btn btn-warning btn-xs") %>
			  <% else %>
				<%= link_to("取消幻灯片", undo_slide_admin_banner_path(banner), method: :post, class: "btn btn-warning btn-xs")  %>
			  <% end %>
			</td>
		</tr>
	  <% end %>
	</tbody>
</table>

app/views/admin/banners/new.html.erb
<h2>New Banner</h2>

<%= render "common/admin_banner_form" %>