config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "products#index"

  get "/pages/:page" => "pages#show"

  namespace :admin do
    resources :products do
      member do
        post :onsale
        post :notsale
      end
      resources :photos, :only => [:destroy]
    end

    resources :banners do
      member do
        post :hide
        post :publish
        post :do_slide
        post :undo_slide
      end
    end

    resources :categories do
      member do
        get :get_subcategories, defaults: { format: "js" }
      end
    end

  end  # namespace admin end

  resources :banners

  resources :products do
    member do
      post :add_to_cart
    end

    collection do
      get :search
      get :new_arrived
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders

  namespace :account do
    resources :orders
  end


  #resources :brands
  resources :categories


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :cover, CoverUploader
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    item = cart_items.where("product_id = ?", product.id)

    if item.size < 1
      ci = cart_items.build
      ci.product = product
      ci.quantity = 1
    else
      ci = item.first
      ci.update_attribute(:quantity, ci.quantity + 1)
    end

    product.quantity -= 1
    product.save

    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    return sum
  end

  def item_total_price(cart_item)
    # item = cart_items.where("product_id = ?", product.id)
    sum = 0

    if cart_item.product.price.present?
      sum += cart_item.quantity * cart_item.product.price
    end

    return sum
  end


  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :presence => true

  scope :main_categories, -> { where(:is_main_category => true) }
  scope :sub_categories, -> { where(:is_main_category => false) }

  has_many :products

  belongs_to :parent_category, :class_name => :Category, :foreign_key => "parent_category_id"
  has_many :children_categories,
          -> { where :is_main_category => false},
          :class_name => :Category,
          :foreign_key => :parent_category_id,
          :primary_key => :id

  def parent_category_name
    self.try(:parent_category).try(:name)
  end



end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lists
  before_create :generate_token

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :order
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  #mount_uploader :photo, PhotoUploader
  belongs_to :category
  belongs_to :brand
  has_many :photos
  accepts_nested_attributes_for :photos

  def onsale!
    self.onsale = true
    self.save
  end

  def notsale!
    self.onsale = false
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
    is_admin
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  layout "admin"

  protect_from_forgery except: :get_subcategories


  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    # @parent_categories = Category.main_categories

    if @category.save
      redirect_to admin_categories_path, :notice => "Category Created"
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to admin_categories_path, :notice => "Category Updated."
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:warning] = "Category Deleted."
    redirect_to admin_categories_path
  end


  def get_subcategories
    @subcategories = Category.where(:parent_category_id => params[:id])
    respond_to do |format|
      format.js
    end
  end


  private

    def category_params
      params.require(:category).permit(:name, :is_main_category, :parent_category_id)
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @main_categories = Category.main_categories
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where(:onsale => true,
                :category_id => @category.id).order("created_at DESC")
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper

  def render_is_main_category(category)
    if category.is_main_category
      "是"
    else
      "否" 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def render_cart_total_price(cart)
    cart.total_price
  end

  def render_cart_item_total_price(cart, cart_item)
    cart.item_total_price(cart_item)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for [:admin, @category] do |f| %>
	<div class="group"><%= f.input :name %></div>
	<div class="group"><%= f.input :is_main_category %></div>
	<div class="group"><%= f.input :parent_category_id, :collection => Category.main_categories %></div>


	<%= f.submit "Submit", data: {disable_with: "Submitting..."} %>

<% end %>

app/views/admin/categories/edit.html.erb
<h2>Edit Category</h2>

<%= render "form" %>

app/views/admin/categories/get_subcategories.js.erb
$("#sub_categories #product_category_id").html('<%=j options_from_collection_for_select(@subcategories, "id", "name") %>');

// <% if @subcategories %>
//   alert("OK");
// <% else %>
//   alert("Fails");
// <% end %>

app/views/admin/categories/index.html.erb
<h2>Category List</h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增 Category", new_admin_category_path, class: "btn btn-primary btn-sm" ) %>
</div>


<table class="table table-bordered">
	<thead>
		<tr>
			<th width="70">#</th>
			<th width="150">分类名称</th>
			<th>是主分类</th>
			<th>所属分类名称</th>
			<th width="250">Options</th>
		</tr>
	</thead>

	<tbody>
	  <% @categories.each do |category| %>
		<tr>
			<td>
				<%= category.id %>
			</td>
			<td>
				<%= category.name %>
			</td>
			<td><%= render_is_main_category(category) %></td>
			<td><%= category.parent_category_name %></td>
			<td>
				<%= link_to("Edit", edit_admin_category_path(category), class: "btn btn-primary btn-xs") %>
				<%= link_to("Delete", admin_category_path(category), method: :delete, class: "btn btn-danger btn-xs", data: {confirm: "确定要删除该 Category 吗？\n#{category.name}" }) %>
			</td>
		</tr>
	  <% end %>
	</tbody>
</table>

app/views/admin/categories/new.html.erb
<h2>New Category</h2>

<%= render "form" %>

app/views/categories/index.html.erb
<div class="wrapper product-wrap">
  <div class="container">

    <div class="row">
			<div class="col-md-12">
        <ol class="breadcrumb breadcrumb-jd">
          <li><a href="/">Home</a></li>
          <li><strong>产品类别</strong></li>
        </ol>
			</div>
		</div>

    <div class="row">
      <div class="col-md-12">
        <div class="page-title category-title">
          <h1>Shop by Category</h1>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <% @main_categories.each do |main_category| %>
          <div class="list-group category-list the-box-shadow">
            <li class="list-group-item list-group-item-info pink"><%= main_category.name %></li>
            <!-- <% if main_category %> -->
              <% main_category.children_categories.each do |sub_category| %>
                <%= link_to( sub_category.name, category_path(sub_category),
                            :class => "list-group-item" ) %>
              <% end %>
            <!-- <% end %> -->
          </div>
        <% end %>

      </div>
    </div>


  </div>
</div>

app/views/categories/show.html.erb
<div class="wrapper product-wrap">
  <div class="container">

    <div class="row">
			<div class="col-md-12">
        <ol class="breadcrumb breadcrumb-jd">
          <li><a href="/">Home</a></li>
          <li><strong><%= @category.name %></strong></li>
        </ol>
			</div>
		</div>

    <div class="row">
      <div class="col-md-12"></div>

        <div class="col-md-2">
          <%= render "common/left_nav" %>
  			</div>

  			<div class="col-md-10">
          <div class="row">

            <% @products.each do |product| %>
            <div class="col-xs-6 col-md-3">
              <div class="thumbnail category-product">

                <%= link_to product_path(product) do %>
                  <% if product.photos.present? %>
                    <%= image_tag(product.photos[0].avatar.big_thumb.url) %>
                  <% else %>
                    <% image_tag("no-pic.png") %>
                  <% end %>
                <% end %>
                <div class="product-info">
                  <div class="cation">
                    <%= link_to product_path(product) do %>
                      <h3 class="product-name"><%= product.title %></h3>
                    <% end %>
                  </div>
                    <div class="product-price-wrap">
                      <div class="product-price">
                        <i>¥</i><%= product.price %>
                      </div>
                      <div class="product-add-cart">
                        <%= link_to add_to_cart_product_path(product), method: :post do %>
                          <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
                        <% end %>
                      </div>
                    </div>

                </div>
              </div>
            </div>
            <% end %>

          </div>
      </div>  <!-- col-md-10 end -->

    </div>     <!-- row end -->


  </div>
</div>