config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "products#index"

  get "/pages/:page" => "pages#show"

  namespace :admin do
    resources :products do
      member do
        post :onsale
        post :notsale
      end
      resources :photos, :only => [:destroy]
    end

    resources :banners do
      member do
        post :hide
        post :publish
        post :do_slide
        post :undo_slide
      end
    end

    resources :categories do
      member do
        get :get_subcategories, defaults: { format: "js" }
      end
    end

  end  # namespace admin end

  resources :banners

  resources :products do
    member do
      post :add_to_cart
    end

    collection do
      get :search
      get :new_arrived
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders

  namespace :account do
    resources :orders
  end


  #resources :brands
  resources :categories


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  #mount_uploader :photo, PhotoUploader
  belongs_to :category
  belongs_to :brand
  has_many :photos
  accepts_nested_attributes_for :photos

  def onsale!
    self.onsale = true
    self.save
  end

  def notsale!
    self.onsale = false
    self.save
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :require_is_admin
  layout "admin"


  def index
    @products = Product.all.order("created_at DESC")
  end

  def new
    @main_categories = Category.main_categories
    @subcategories = Category.where(:parent_category_id => @main_categories.first.id)
    @product = Product.new
    @photo = @product.photos.build # for multi-pics
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      if params[:photos] != nil
        params[:photos]['avatar'].each do |a|
          @photo = @product.photos.create(:avatar => a)
        end
      end
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @photos = @product.photos

    @main_categories = Category.main_categories
    @subcategories = Category.where(:parent_category_id => @main_categories.first.id)
  end

  def update
    @product = Product.find(params[:id])


    if params[:photos] != nil
      @product.photos.destroy_all  # need to destroy old pics first

      params[:photos]['avatar'].each do |a|
        @picture = @product.photos.create(:avatar => a)
      end

      @product.update(product_params)
      redirect_to admin_products_path

    elsif @product.update(product_params)
      redirect_to admin_products_path, notice: "Product Updated."
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product deleted."
    redirect_to admin_products_path
  end

  def onsale
    @product = Product.find(params[:id])
    @product.onsale!

    redirect_to :back
  end

  def notsale
    @product = Product.find(params[:id])
    @product.notsale!

    redirect_to :back
  end


  private

    def product_params
      params.require(:product).permit(:title, :description, :price, :quantity, :photo, :onsale, :category_id, :author)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]
  # before_action :set_search

  def index
    @products = Product.where("onsale = ?", true).paginate(:page => params[:page], :per_page => 12)
    @slides = Banner.where("is_hidden = ? AND is_slide = ?", false, true )
    @banners = Banner.where("is_hidden = ? AND is_slide = ?", false, false ).order("created_at
                           DESC").limit(2)
    # @q = Product.ransack(params[:q])
    @picture_books = Product.where("onsale = ? AND category_id = ?", true, 60).order("created_at DESC").limit(6)
    @new_arrives = Product.where("onsale = ?", true).order("created_at DESC").limit(6)
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
    @category = Category.where("id = ?", @product.category_id).first
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_product_to_cart(@product)

    redirect_to :back
  end

  def search
    if @query_string.present?
      @q = Product.ransack(@search_criteria)
      @products = @q.result(:distinct => true).paginate(:page => params[:page], :per_page => 12)
    end

    # @q = Product.ransack(params[:q])
    # @products = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 12)

  end

  def new_arrived
    @products = Product.where("onsale = ?", true).order("created_at DESC").limit(20)
  end



  protected

    def validate_search_key
      @query_string = params[:q].gsub(/\\|\'|-|\/|\.|\?/, "") if params[:q].present?
      @search_criteria = {
        :title_cont => @query_string
      }

    end


    #
    # def set_search
    #   @q = Product.search(params[:id])
    # end



end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def render_product_onsale(product)
    if product.onsale
      content_tag(:span, "", :class => "fa fa-globe")
    else
      content_tag(:span, "", :class => "fa fa-lock")
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
	<div class="group"><%= f.input :title, placeholder: "请输入产品标题" %></div>
	<div class="group"><%= f.input :author, placeholder: "请输入产品作者" %></div>
	<div class="group"><%= f.input :description, placeholder: "请输入产品描述" %></div>
	<div class="group"><%= f.input :quantity, placeholder: "请输入产品数量" %></div>
	<div class="group"><%= f.input :price, placeholder: "请输入产品价格" %></div>
	<div class="group" id="main_categories"><%= f.input :category_id,
									:collection => @main_categories,
									label: "Main Category",
									prompt: "请选择产品所属主类",
									:remote => true %></div>
	<div class="group" id="sub_categories"><%= f.input :category_id,
									:collection => @subcategories,
									label: "Sub Category",
									prompt: "请选择产品所属子类",
									class: "sub_categories" %></div>

	<div class="group">
	<% if @product.photos.count > 1 %>
		<%= f.label "目前商品图" %><br>
	  <div class="avatar-thumbs">
	    <% @product.photos.each do |pic, index| %>
			<div class="avatar-thumb">
				<%= image_tag pic.avatar.big_thumb.url %>
				<%= link_to admin_product_photo_path(@product, pic), method: :delete, class: "delete" do %>
					<i class="fa fa-trash delete red"></i>
				<% end %>
			</div>
		  <% end %>
	  </div>
    <% end %>
	</div>
	<div class="group">
	  <%= f.label :avatar %><br>
	  <%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %><br>
	</div>
	<div class="group"><%= f.input :onsale %></div>

	<%= f.submit "Submit", data: {disable_with: "Submitting..."} %>

<% end %>

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>

<%= render "form" %>

app/views/admin/products/index.html.erb
<h2>Product List</h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm" ) %>
</div>

<table class="table table-bordered">
	<thead>
		<tr>
			<th width="60">#</th>
			<th width="220">Product Pic</th>
			<th>Title</th>
			<th>Author</th>
			<th>Price</th>
			<th width="150">Options</th>
		</tr>
	</thead>

	<tbody>
	  <% @products.each do |product| %>
		<tr>
			<td>
				<%= product.id %>
				<%= render_product_onsale(product) %>
			</td>
			<td>
				<%= link_to product_path(product) do %>
				  <% if product.photos.present? %>
					  <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
				  <% end %>
				<% end %>
			</td>
			<td><%= product.title %></td>
			<td><%= product.author %></td>
			<td><%= product.price %></td>
			<td>
				<%= link_to("Edit", edit_admin_product_path(product), class: "btn btn-primary btn-xs") %>
				<%= link_to("Delete", admin_product_path(product), method: :delete, class: "btn btn-danger btn-xs", data: {confirm: "确定要删除该产品吗？\n#{product.title}" }) %>
			  <% if product.onsale %>
				<%= link_to("下架", notsale_admin_product_path(product), method: :post, class: "btn btn-info btn-xs") %>
			  <% else %>
				<%= link_to("上架", onsale_admin_product_path(product), method: :post, class: "btn btn-info btn-xs")  %>
			  <% end %>
			</td>
		</tr>
	  <% end %>
	</tbody>
</table>

app/views/admin/products/new.html.erb
<h2>New Product</h2>

<%= render "form" %>