config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "products#index"

  get "/pages/:page" => "pages#show"

  namespace :admin do
    resources :products do
      member do
        post :onsale
        post :notsale
      end
      resources :photos, :only => [:destroy]
    end

    resources :banners do
      member do
        post :hide
        post :publish
        post :do_slide
        post :undo_slide
      end
    end

    resources :categories do
      member do
        get :get_subcategories, defaults: { format: "js" }
      end
    end

  end  # namespace admin end

  resources :banners

  resources :products do
    member do
      post :add_to_cart
    end

    collection do
      get :search
      get :new_arrived
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders

  namespace :account do
    resources :orders
  end


  #resources :brands
  resources :categories


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :cover, CoverUploader
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    item = cart_items.where("product_id = ?", product.id)

    if item.size < 1
      ci = cart_items.build
      ci.product = product
      ci.quantity = 1
    else
      ci = item.first
      ci.update_attribute(:quantity, ci.quantity + 1)
    end

    product.quantity -= 1
    product.save

    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    return sum
  end

  def item_total_price(cart_item)
    # item = cart_items.where("product_id = ?", product.id)
    sum = 0

    if cart_item.product.price.present?
      sum += cart_item.quantity * cart_item.product.price
    end

    return sum
  end


  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :presence => true

  scope :main_categories, -> { where(:is_main_category => true) }
  scope :sub_categories, -> { where(:is_main_category => false) }

  has_many :products

  belongs_to :parent_category, :class_name => :Category, :foreign_key => "parent_category_id"
  has_many :children_categories,
          -> { where :is_main_category => false},
          :class_name => :Category,
          :foreign_key => :parent_category_id,
          :primary_key => :id

  def parent_category_name
    self.try(:parent_category).try(:name)
  end



end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lists
  before_create :generate_token

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :order
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  #mount_uploader :photo, PhotoUploader
  belongs_to :category
  belongs_to :brand
  has_many :photos
  accepts_nested_attributes_for :photos

  def onsale!
    self.onsale = true
    self.save
  end

  def notsale!
    self.onsale = false
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
    is_admin
  end

end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def render_cart_total_price(cart)
    cart.total_price
  end

  def render_cart_item_total_price(cart, cart_item)
    cart.item_total_price(cart_item)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_admin_banner_form.html.erb
<%= simple_form_for [:admin, @banner] do |f| %>
	<div class="group"><%= f.input :title %></div>
	<div class="group"><%= f.input :description %></div>
	<div class="group"><%= f.input :link %></div>
	<div class="group"><%= f.input :is_slide %></div>
	<% if @banner.cover.present? %>
		<span>目前 Banner 图片</span><br>
		<%= image_tag(@banner.cover.thumb.url, class: "thumbnail") %>
    <% end %>

	<div class="group"><%= f.input :cover, as: :file %></div>
	<div class="group"><%= f.input :is_hidden %></div>

	<%= f.submit "Submit", data: {disable_with: "Submitting..."} %>

<% end %>

app/views/common/_admin_category_form.html.erb
<%= simple_form_for [:admin, @category] do |f| %>
	<div class="group"><%= f.input :name %></div>
	<div class="group"><%= f.input :is_main_category %></div>
	<div class="group"><%= f.input :parent_category_id, :collection => Category.main_categories %></div>


	<%= f.submit "Submit", data: {disable_with: "Submitting..."} %>

<% end %>

app/views/common/_admin_footer.html.erb
<footer class="container">
	<p class="text-center">Copyright ©2016 JDStore
		<br> Design by liuzx
	</p>
</footer>

app/views/common/_admin_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">JDStore.4</a>
		</div>

		<div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<%= link_to("Products", products_path) %>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<!-- search form -->
				<li>
					<section id="search_section">
					<%= form_tag search_products_path, :method => :get  do %>
						<div class="wrapper">
							<input type="search" name="q" value="<%= params[:q] %>" placeholder="请输入要搜索的信息">
						</div>
					<% end %>
				 </section>
				</li>
				<!-- minicart -->
				<%= render "common/minicart" %>


				  <% if !current_user %>
					  <li><%= link_to("注册", new_user_registration_path) %></li>
					  <li><%= link_to(content_tag(:i, " 登入", class: "fa fa-sign-in"), new_user_session_path) %></li>
				  <% else %>
					  <li class="dropdown">
						  <a class="dropdown-toggle" href="#" data-toggle="dropdown">
							  Hi!, <%= current_user.email %>
							  <b class="caret"></b>
						  </a>
						  <ul class="dropdown-menu">
							<% if current_user.admin? %>
								<li><%= link_to("Admin Panel", admin_products_path) %></li>
							<% end %>
							<li><%= link_to("历史订单", account_orders_path) %></li>
						    <li><%= link_to(content_tag(:i, "登出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete) %></li>
						  </ul>
					  </li>
				  <% end %>
			</ul>
		</div>
	</div>
</nav>




<!-- <div class="wrapper header-bottom">
	<div class="container">
		<div class="row">
			<div class="col-md-2 col-xs-4 nav-1">
				<a href="#">产品类别</a>

			</div>
			<div class="col-md-2 col-xs-4 nav-2"><a href="#">产品品牌</a></div>
			<div class="col-md-2 col-xs-4 nav-3"><a href="#">新品上市</a></div>
			<div class="col-md-2 col-xs-4"><a href="#">优品特惠</a></div>
			<div class="col-md-2 col-xs-4"><a href="#">热销精品</a></div>
			<div class="col-md-2 col-xs-4"><a href="#">今日特价</a></div>
		</div>
	</div>
</div> -->

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
	  <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
		  <button class="close" data-dismiss="alert">x</button>
		  <%= value %>
	  </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<div class="wrapper footer-nav-container">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="footer-nav">
					<div class="footer-nav-list">
							<h5 class="footer-nav-title">关于我们</h5>
							<ul class="footer-nav-links">
								<li><a href="#">关于我们</a></li>
								<li><a href="#">隐私政策</a></li>
								<li><a href="#">服务条款</a></li>
								<li><a href="#">常见问题</a></li>
							</ul>
					</div>

					<div class="footer-nav-list">
							<h5 class="footer-nav-title">会员服务</h5>
							<ul class="footer-nav-links">
								<li><a href="#">加入会员</a></li>
								<li><a href="#">新手上路</a></li>
								<li><a href="#">会员分级</a></li>
								<li><a href="#">订阅消息</a></li>
								<li><a href="#">客服中心</a></li>
							</ul>
					</div>

					<div class="footer-nav-list">
							<h5 class="footer-nav-title">配送支付</h5>
							<ul class="footer-nav-links">
								<li><a href="#">上门自提</a></li>
								<li><a href="#">配送查询</a></li>
								<li><a href="#">货到付款</a></li>
								<li><a href="#">在线支付</a></li>
								<li><a href="#">分期付款</a></li>
							</ul>
					</div>

					<div class="footer-nav-list">
							<h5 class="footer-nav-title">售后服务</h5>
							<ul class="footer-nav-links">
								<li><a href="#">售后政策</a></li>
								<li><a href="#">价格保护</a></li>
								<li><a href="#">退款说明</a></li>
								<li><a href="#">返修/退换货</a></li>
								<li><a href="#">取消订单</a></li>
							</ul>
					</div>

				</div>
			</div>
			<div class="col-md-4">
				<div class="block-contact-wrapper">
				 <div class="block-contact">
						<div class="block-title">
							<span>联系我们</span>
						</div>
						<div class="block-content">
							<p>在购物中思考‧在阅读中進化</p>
							<a href="#"><i class="fa fa-envelope-o fa-2x" aria-hidden="true"></i></a>
						</div>
				 </div>
			 </div>
			</div>

		</div>
	</div>
</div>

<div class="wrapper footer-container">
	<div class="container">
	<div class="row">
		<div class="col-md-8">
			<p class="footer-copyright">Copyright ©2017 National Book Store Inc. All Rights Reserved. |
				<a href="#">Design by liuzx & liulp</a>
			</p>
		</div>
		<div class="col-md-4 payment">
			<a href="#"><%= image_tag("visa.png") %></a>
			<a href="#"><%= image_tag("mc.png") %></a>
			<a href="#"><%= image_tag("paypal.png") %></a>
		</div>
	</div>
	</div>
</div>

app/views/common/_left_nav.html.erb
<div class="left_nav">

  <h3>Popular in Books</h3>
  <ul>
    <li><a href="#">Some Books</a></li>
    <li><a href="#">Some Books</a></li>
    <li><a href="#">Some Books</a></li>
    <li><a href="#">Some Books</a></li>
  </ul>

  <h3>Popular in Books</h3>
  <ul>
    <li><a href="#">Some Books</a></li>
    <li><a href="#">Some Books</a></li>
    <li><a href="#">Some Books</a></li>
    <li><a href="#">Some Books</a></li>
  </ul>


</div>

app/views/common/_left_nav_about.html.erb
<div class="left_nav">

  <h3>关于我们</h3>
  <ul>
    <li><a href="#">关于我们</a></li>
    <li><a href="#">隐私政策</a></li>
    <li><a href="#">服务条款</a></li>
    <li><a href="#">常见问题</a></li>
  </ul>


  <h3>会员服务</h3>
  <ul>
    <li><a href="#">加入会员</a></li>
    <li><a href="#">新手上路</a></li>
    <li><a href="#">会员分级</a></li>
    <li><a href="#">订阅消息</a></li>
    <li><a href="#">客服中心</a></li>
  </ul>

  <h3>配送支付</h3>
  <ul>
    <li><a href="#">上门自提</a></li>
    <li><a href="#">配送查询</a></li>
    <li><a href="#">在线支付</a></li>
    <li><a href="#">分期付款</a></li>
  </ul>

  <h3>售后服务</h3>
  <ul>
    <li><a href="#">售后政策</a></li>
    <li><a href="#">价格保护</a></li>
    <li><a href="#">退款说明</a></li>
    <li><a href="#">返修/退换货</a></li>
    <li><a href="#">取消订单</a></li>
  </ul>


</div>

app/views/common/_minicart.html.erb
<li id="mycart" class="dropdown">
  <%= link_to carts_path do %>
    <i class="fa fa-shopping-cart red" aria-hidden="true"></i>
    购物车<span class="cart-badge"> <%= current_cart.products.count %></span>
  <% end %>

  <div class="cart-dropdown">
    <h4>新添加的商品</h4>
    <div class="clr"></div>
    <div id="cart-content">

      <% current_cart.cart_items.each do |cart_item| %>

      <div class="clr"></div>
      <div class="mcart-ci">
        <div class="ci_t">
          <div class="fl"><span>满减</span>购满199元，即可享受满减优惠
          </div>
          <div class="fr">小计：￥<%= render_cart_item_total_price(current_cart, cart_item) %></div>
          <div class="clr"></div>
        </div>

        <div class="ci_content">
          <div class="p-img fl">
            <%= link_to product_path(cart_item.product) do %>
              <% if cart_item.product.photos.present? %>
      				  <%= image_tag(cart_item.product.photos[0].avatar.thumb.url, style: "width: 50px; height: 50px;") %>
      			  <% else %>
      				  <%= image_tag("no-pic.png", style: "width: 50px; height: 50px;") %>
      			  <% end %>
            <% end %>
            </a>
          </div>
          <div class="p-name fl"><%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
          </div>
          <div class="p-detail fr">
            <span class="p-price">
              <strong>¥ <%= cart_item.product.price %></strong>
              x<%= cart_item.quantity %>
            </span>
            <br>
            <%= link_to cart_item_path(cart_item.product_id), method: :delete,
                    data: { confirm: "确定要将此商品从购物车中删除吗？"} do %>
    				  <i class="fa fa-trash"></i>
    			  <% end %>
            <!-- <a href="#" class="delete">删除</a> -->
          </div>
        </div>
      </div>

      <% end %>

      <div class="clr"></div>



  </div>
  <div class="cart-footer">
    <div class="p-total">
      共 <b><%= current_cart.products.count %></b> 件商品 共计
      <strong>¥ <%= render_cart_total_price(current_cart) %></strong>
    </div>
    <%= link_to "去购物车", carts_path %>

    <!-- <a href="#">去购物车</a> -->

  </div>

</li>

app/views/common/_my_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @slides.each_with_index do |slide, i| %>
	  <li data-target="#myCarousel" data-slide-to="<%= i %>" <% if i == 0 %>class="active"<% end %>></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @slides.each_with_index do |slide, i| %>
		<div class="item <% if i == 0 %>active<% end %>">
			<%= link_to image_tag(slide.cover.url, size: "710x472"),
				slide.link,
				:target => "_blank" %>
        <div class="carousel-caption">
          <h3><%= slide.title %></h3>
          <p><%= slide.description %></p>
        </div>
      </div>
    <% end %>


  </div>

  <!-- Left and right controls -->
  <!-- <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left " aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a> -->
</div>

app/views/common/_navbar.html.erb
<div class="wrapper header-top">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-6">
				<p class="welcome-msg"> 购物满 199 立减 30 </p>
			</div>
			<div class="col-md-8 col-xs-12">
				<ul>
					<li><i class="fa fa-user-circle-o h_i"></i>
						<%= link_to "免费注册", new_user_registration_path %>
					</li>
					<li><i class="fa fa-shopping-bag h_i"></i>
						<%= link_to "我的订单", account_orders_path %>
					</li>
					<li><i class="fa fa-star h_i"></i>
						<%= link_to "精选分类", categories_path %>
					</li>
					<li><i class="fa fa-gift h_i"></i>
						<%= link_to "最新产品", new_arrived_products_path %>
					</li>
					<li><i class="fa fa-check-circle h_i"></i>
						<%= link_to "关于我们", "/pages/about" %>
					</li>
					<li><i class="fa fa-phone h_i"></i>
						<%= link_to "客户服务", "/pages/about" %>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="wrapper header-middle">
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a href="/"><%= image_tag("logo2.png", style: "width:239px; height: 52px;")  %></a>
		</div>

		<div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<!-- search form -->
				<li>
					<section id="search_section">
					<%= form_tag search_products_path, :method => :get  do %>
						<div class="wrapper">
							<input type="search" name="q" value="<%= params[:q] %>" placeholder="请输入要搜索的信息">
						</div>
					<% end %>
				 </section>
				</li>
				<!-- minicart -->
				<%= render "common/minicart" %>


				  <% if !current_user %>
					  <li><%= link_to("注册", new_user_registration_path) %></li>
					  <li><%= link_to(content_tag(:i, " 登入", class: "fa fa-sign-in"), new_user_session_path) %></li>
				  <% else %>
					  <li class="dropdown">
						  <a class="dropdown-toggle" href="#" data-toggle="dropdown">
							  Hi!, <%= current_user.email %>
							  <b class="caret"></b>
						  </a>
						  <ul class="dropdown-menu">
							<% if current_user.admin? %>
								<li><%= link_to("Admin Panel", admin_products_path) %></li>
							<% end %>
							<li><%= link_to("历史订单", account_orders_path) %></li>
						    <li><%= link_to(content_tag(:i, "登出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete) %></li>
						  </ul>
					  </li>
				  <% end %>
			</ul>
		</div>

	</div>
</nav>
</div>

<div class="wrapper header-bottom">
	<div class="container">
		<div class="row">
			<div class="col-md-2 col-xs-4 nav-1">
				<%= link_to("产品类别", categories_path) %>
			</div>
			<div class="col-md-2 col-xs-4 nav-2">
				<%= link_to("产品品牌", categories_path) %>
			</div>
			<div class="col-md-2 col-xs-4 nav-3">
				<%= link_to("新品上市", new_arrived_products_path) %>
			</div>
			<div class="col-md-2 col-xs-4">
				<%= link_to("优品特惠", categories_path) %>
			</div>
			<div class="col-md-2 col-xs-4">
				<%= link_to("热销精品", categories_path) %>
			</div>
			<div class="col-md-2 col-xs-4">
				<%= link_to("今日特价", categories_path) %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>National Book Store Admin</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
	<div class="container">
		<%= render "common/admin_navbar" %>
    <%= render "common/flashes" %>
		<div class="row">
			<div class="col-md-2">
				<ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
					<li><%= link_to("Products", admin_products_path) %></li>
					<li><%= link_to("Banners", admin_banners_path) %></li>
          <li><%= link_to("Categories", admin_categories_path) %></li>
				</ul>
			</div>

			<div class="col-md-10">
				<%= yield %>
			</div>
		</div>
	</div>
  <%= render "common/admin_footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>National Book Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
	  <!-- <div class="container-fluid"> -->
		    <%= render "common/navbar" %>
		    <%= render "common/flashes" %>
		    <%= yield %>
	  <!-- </div> -->
	  <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>National Book Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
	  <!-- <div class="container-fluid"> -->
    <%= render "common/navbar" %>
    <%= render "common/flashes" %>

      <div class="wrapper product-wrap">
        <div class="container">

          <div class="row">
      			<div class="col-md-12">
              <ol class="breadcrumb breadcrumb-jd">
                <li><a href="/">Home</a></li>
                <li><strong>服务中心</strong></li>
              </ol>
      			</div>
      		</div>

          <div class="row">
            <div class="col-md-12"></div>

              <div class="col-md-2">
                <%= render "common/left_nav_about" %>
        			</div>

        			<div class="col-md-10">
                <div class="row">
                  <div class="col-md-12">
                    <%= yield %>
                  </div>


                </div>
            </div>  <!-- col-md-10 end -->

          </div>     <!-- row end -->


        </div>
      </div>


	  <!-- </div> -->
	  <%= render "common/footer" %>
  </body>
</html>